name: CI/CD Digital Ocean

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: cd api && npm install && npm run build

      - name: Upload to Digital Ocean
        uses: appleboy/scp-action@master # This is the action
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: 'api/dist' # Path to the directory you want to copy
          target: '~/' # Path to the directory you want to copy to

      - name: Start Server
        uses: appleboy/ssh-action@v0.1.4 # This is the action
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
          passphrase: ${{ secrets.SSH_PASSPHRASE }}

          script: |
            rm -rf ~/Vita
            git clone https://github.com/Vita-App/Vita.git
            mv api/dist Vita/api/
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/Vita/api && npm install && cd ~/ && rm api
            pm2 stop vita-server
            pm2 start ~/env/ecosystem.config.js --env production
            echo 'Deployment successful to digital ocean'
